name: PVPpl
version: '1.0-SNAPSHOT'
main: org.mcmod.pVPpl.PVPpl
api-version: '1.21'
commands:
  pvp:
    description: PVP game admin command
    usage: /pvp <start|stop|help|config|info|history|mode|teamsize>
    aliases:
      - pvpgame
  tab:
    description: Tab list config command
    usage: /tab config
    permission: pvppl.admin
  top:
    description: Teleport to surface once per game
    usage: /top
permissions:
  pvppl.admin:
    description: Admin permission for PVP plugin
    default: op

