name: PVPpl
version: '1.0-SNAPSHOT'
main: org.mcmod.pVPpl.PVPpl
api-version: '1.21'
commands:
  pvp:
    description: PVP 게임을 관리합니다.
    usage: /pvp <start|stop|help>
    aliases:
      - pvpgame
permissions:
  pvppl.admin:
    description: 게임 관리자 권한
    default: op
